version: '3'

services:

    db:
        image: postgres
        volumes:
            - ./.docker_data/postgres:/var/lib/postgresql/data
        ports:
            - 5432:5432

    vpn:
        image: privatix/dapp-vpn-server
        ports:
            - 1194:1194
            - 7505:7505
        privileged: true

    dappctrl:
        image: privatix/dappctrl
        ports:
            - 8080:8080
            - 9000:9000
        depends_on:
            - db
            - vpn
